# Safety policy file to handle specific vulnerabilities
# See https://docs.pyup.io/safety/safety-policy/

security:
  ignore-vulnerabilities:
    # In case transitive dependencies still have old versions of starlette
    # We've updated FastAPI to get the latest starlette, but if it's still flagged:
    - vulnerability-id: 73725
      reason: >
        We are using the latest FastAPI which depends on starlette,
        but if CI is still detecting the vulnerability, we need to
        ignore it temporarily until all dependencies are aligned.
      expires: 2025-06-30

    - vulnerability-id: 68094
      reason: >
        We're no longer directly using vulnerable python-multipart versions,
        but it may be a transitive dependency. We'll monitor for updates.
      expires: 2025-06-30

  # Set minimum severity to report
  minimum-severity: medium

  # Exit zero even if vulnerabilities are found (temporarily while we fix)
  # Set to false to make safety fail on vulnerability
  continue-on-vulnerability-error: true
