version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5001:5001"
    environment:
      - DEBUG=False
      - PRODUCTION=True
      - API_PREFIX=/api
      - HOST=0.0.0.0
      - PORT=5001
      - ALLOW_ORIGINS=${ALLOW_ORIGINS:-https://kitwanaakil.com,https://admin.kitwanaakil.com}
      - LOG_LEVEL=INFO
      - API_KEY=${API_KEY}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-https://api.kitwanaakil.com}
      - ENABLE_HTTPS_REDIRECT=True
    volumes:
      - carousel_temp:/app/static/temp
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - carousel-prod-network

volumes:
  carousel_temp:
    driver: local

networks:
  carousel-prod-network:
    driver: bridge
