version: '3.8'

services:
  # FastAPI application
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - ./static:/app/static
    expose:
      - "5001"
    environment:
      - DEBUG=True
      - API_PREFIX=/api
      - HOST=0.0.0.0
      - PORT=5001
      - ALLOW_ORIGINS=*
      - LOG_LEVEL=DEBUG
      - PUBLIC_BASE_URL=http://localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - carousel-network
    depends_on:
      - redis

  # Nginx for serving static files and proxying
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - api
    networks:
      - carousel-network

  # Redis for caching and rate limiting
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - carousel-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development tools - Swagger UI for API documentation
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://localhost/openapi.json
    depends_on:
      - api
      - nginx
    networks:
      - carousel-network

  # Development tools - Documentation site
  docs:
    image: nginx:alpine
    volumes:
      - ./docs:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - carousel-network

volumes:
  redis_data:
    driver: local

networks:
  carousel-network:
    driver: bridge
