version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "5001:5001"
    environment:
      - DEBUG=True
      - API_PREFIX=/api
      - HOST=0.0.0.0
      - PORT=5001
      - LOG_LEVEL=DEBUG
      - ALLOW_ORIGINS_STR=*
      - ALLOW_METHODS_STR=*  # Updated field name
      - ALLOW_HEADERS_STR=*  # Updated field name
      - ALLOW_CREDENTIALS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - carousel-network

  # Add a development tool container with documentation
  docs:
    image: nginx:alpine
    volumes:
      - ./docs:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - carousel-network
    command: sleep infinity

networks:
  carousel-network:
    driver: bridge
