name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow running manually from the Actions tab
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install safety

    - name: Run safety check
      run: |
        safety check --policy-file .safety-policy.yml
