name: Test Secrets Setup

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'email'
        type: choice
        options:
        - email
        - ssh

jobs:
  test-email-secrets:
    if: ${{ github.event.inputs.test_type == 'email' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "✅ GitHub Secrets Test"
          body: "This is a test email to verify your GitHub Secrets configuration is working correctly."
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: GitHub Actions Test

  test-ssh-secrets:
    if: ${{ github.event.inputs.test_type == 'ssh' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          # Add server to known hosts
          mkdir -p ~/.ssh
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          
          # Test SSH connection
          if ssh $SERVER_USER@$SERVER_IP "echo 'SSH connection successful'"; then
            echo "✅ SSH connection test passed"
          else
            echo "❌ SSH connection test failed"
            exit 1
          fi